ui: mocha-bdd
browsers:
  - name: internet explorer
    version: 6..latest
  - name: microsoftedge
    version: latest
  - name: safari
    version: 5..latest
  - name: chrome
    version: [26, 30, 35, 40, -1..latest]
  - name: firefox
    version: [15, 20, 25, 30, 35, -1..latest]
  - name: opera
    version: 11..latest
  - name: iphone
    version: ['5.1', '6.1', '7.1', '8.4', 'latest']
  - name: ipad
    version: ['5.1', '6.0', '7.0', '8.0', '8.4', 'latest']
  - name: android
    version: ['4.0', '4.4..latest']
